a=int(input("enter a number: "))
b=int(input("enter b number: "))
print("addation of two numbers is", a+b)
print("substraction of two numbers is", a-b)
print("multiplication of two numbers is", a*b)
print("division of two numbers is", a/b)
print("modulo of two numbers is", a%b)
print("floor division of two numbers is", a//b)
print("power of two numbers is", a**b)